Docs: Add KDP offline install docs
linktimecloud/kubernetes-data-platform pull request #135
Opened 2024-06-21 07:02 UTC by stdnt-xiao

### Description of your changes
Docs: Add KDP offline install docs

2024-07-03 02:37 UTC, jason-ltc requested changes

2024-07-03 02:37 UTC, jason-ltc commented on docs/zh/getting-started/images/fluxcd-update.png
This should be modified on the code level.

2024-07-03 05:13 UTC, stdnt-xiao commented on docs/zh/getting-started/images/fluxcd-update.png
fix

2024-07-09 10:12 UTC, jason-ltc approved these changes

2024-07-09 10:13 UTC, merged